# Generated by Django 3.0.7 on 2021-04-09 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('fund_name', models.CharField(max_length=200)),
                ('fund_acquired_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fund_acquired_date', models.DateField(default=django.utils.timezone.now)),
                ('fund_recent_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fund_recent_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='portfolio.Customer')),
            ],
        ),
    ]
